---
  kind: Deployment
  apiVersion: extensions/v1beta1
  metadata:
    name: styles
    namespace: dolittle
  spec:
    template:
      metadata:
        labels:
          app: styles
          name: styles
      spec:
        containers:
        - name: styles
          image: dolittle/styles
          imagePullPolicy: Always
          ports:
          - containerPort: 80
---
  apiVersion: v1
  kind: Service
  metadata:
    name: styles
    namespace: dolittle
    labels:
      app: styles
  spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      name: styles-port
      protocol: TCP
    selector:
      app: styles
      name: styles
  