---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: styles
  namespace: websites
spec:
  selector:
    matchLabels:
      name: styles
  template:
    metadata:
      labels:
        name: styles
    spec:
      containers:
      - name: styles
        image: dolittle/styles
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: http
        resources:
          limits:
            cpu: 250m
            memory: 100Mi          
---
  apiVersion: v1
  kind: Service
  metadata:
    name: styles
    namespace: websites
  spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: http
      name: http
    selector:
      name: styles
  